tpm2-software/tpm2-software-container

Dockerfile
The tpm2-tools CI needs cpp-coveralls installed to provide the coveralls
command.
Signed-off-by: Joshua Lock <joshua.g.lock@intel.com>
=> Dockerfile: install cpp-coveralls

Dockerfile
The [tpm2-pkcs11](https://github.com/tpm2-software/tpm2-pkcs11/) CI requires [SQLite3](https://github.com/tpm2-software/tpm2-pkcs11/blob/a32f9765afc9d9475ca9aa0968c1929f806bcbc2/configure.ac#L71) and the Python modules [PyYAML](https://github.com/tpm2-software/tpm2-pkcs11/blob/a32f9765afc9d9475ca9aa0968c1929f806bcbc2/tools/tpm2_pkcs11/tpm2.py#L9) and [cryptography](https://github.com/tpm2-software/tpm2-pkcs11/blob/a32f9765afc9d9475ca9aa0968c1929f806bcbc2/tools/tpm2_pkcs11/utils.py#L8), both for Python 2 and 3.
=> Dockerfile: install dependencies for tpm2-pkcs11

Dockerfile, README.md
clang++ is required for [fuzzing of tpm2-tss](https://github.com/tpm2-software/tpm2-tss/blob/cdad427c9f38001ed432fb4324568d0c228436d9/Dockerfile#L57). This helps unifying the currently separate [tpm2-tss project Dockerfile](https://github.com/tpm2-software/tpm2-tss/blob/master/Dockerfile).
Additionally fix a typo and link to the Docker Hub image.
=>  Configure clang++ 6.0 using update-alternatives

Dockerfile, fedora-30.docker, opensuse-leap.docker, ubuntu-16.04.docker, ubuntu-18.04.docker
The tcti-swtpm requires swtpm and its dependencies (e.g. libtpms).
Signed-off-by: Johannes Holland <johannes.holland@infineon.com>
=> Add swtpm and its dependencies

Dockerfile, fedora-30.docker, opensuse-leap.docker, ubuntu-16.04.docker, ubuntu-18.04.docker
I made sure that the test suites of all tpm2-software projects pass with the latest version of the simulator (see e.g. tpm2-software/tpm2-tss#1585) once tpm2-software/tpm2-pkcs11#411 is merged, the latter being the main reason for this update.
=> Update ibmswtpm2 to latest version 1563

fedora-30.docker, fedora-32.docker, opensuse-leap-15.2.docker, opensuse-leap.docker, ubuntu-16.04.docker, ubuntu-18.04.docker, ubuntu-20.04.docker
See for details:
- https://github.com/kgoldman/ibmswtpm2/pull/4
TL;DR the available version doesn't have enough memory with RSA
bumped to 3072 to be PC Client Spec compatible and it causes
issues with the RM.
Signed-off-by: William Roberts <william.c.roberts@intel.com>
=> docker: fix v1638 MSSIM available memory

README.md, ubuntu-20.04.docker
I've added mbedTLS to the Ubuntu 20.04 image. This adds the possibility run all test cases with mbedTLS as crypto backend. I have intentionally not added mbedTLS to any of the other images, this allows us to test the build when mbedTLS is not present.
While tasting the changes locally, I noticed that the command line had `--env` instead of `--env-file`. I decided to fix in the same PR. But If requested, I can split it into a second PR.
=> Preparing CI for tpm2-tss w/ mbedTLS

fedora-30.docker, fedora-32.docker, opensuse-leap-15.2.docker, opensuse-leap.docker, ubuntu-16.04.docker, ubuntu-18.04.docker, ubuntu-20.04.docker
When compining against tpm2-tss 2.4.x, this fails due to AM_PATH_LIBGCRYPT not found for all tpm2-tools things.
I think we need to keep libgcrypt in here, until we eol 2.4.x
=> Revert "Remove libgcrypt"

README.md
First, add a title to `README.md` that states that this is the README of `tpm2-software-container` project. Otherwise the README which is display on pages such as https://github.com/orgs/tpm2-software/packages/container/package/fedora-32
looks misplaced (the first sentence starts with "This repository" even though it is associated with a Docker image...).
Secondly, add links to various places and document using Podman, which can be used on systems where the user is not root (and thus should not be in the `docker` group, as this is the same as being root according to https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user).
Finally, update the documented commands because `docker build .` does not work: there is no `Dockerfile` in the git repository. The …
=> README: add title, links and references to Podman, and update commands

modules/ibmtpm1637.m4
When extracting `ibmtpm1637.tar.gz` in a container created with Podman (using user namespaces), several errors occur such as:
tar: ./LICENSE: Cannot change ownership to uid 339315, gid 578953: Invalid argument
tar: ./ibmtpm.doc: Cannot change ownership to uid 339315, gid 578953: Invalid argument
...
Use option `--no-same-owner` (which is enabled by default for non-root users) in order to extract files without taking into account the owner given by the archive.
=> modules/ibmtpm1637: do not preserve owner when extracting the archive

modules/autoconf.m4, modules/ibmtpm1637.m4, modules/junit.m4, modules/pip3.m4, modules/python3.7.2.m4, modules/swtpm.m4, modules/uthash.m4
Hello,
When building some images on a system with 60 GB free disk space, the build fails with "no space left on device". This is caused by the large number of layers which are created for each image.
Minimize the number of intermediate layers by combining all `RUN` statements together in each module, when this is appropriate.
Also use `cd ...` instead of `WORKDIR` statements to also reduce the number of intermediate layers.
With this, `podman build -f ./fedora-32.docker` succeeds on my test system which has "only" 60 GB free disk space.
=> modules: merge RUN commands together

modules/pip3.m4
When pinning a version with pip, if pip doesnt see all the installs at
once it tries to upgrade package versions even if they satisfy the
requirement. This causes issues since cryptograpy > 3.4.8 requires RUST
and some images don't have a new enough rust toolchain and thus the
wheel wont build. To fix this, run pip install and in one command with
all packages.
Signed-off-by: William Roberts <william.c.roberts@intel.com>
=> modules: ensure that pip sees all dependencies

.github/workflows/main.yml, .github/workflows/publish.yml, modules/mbedtls31.m4, ubuntu-22.04-mbedtls-3.1.docker.m4
mbedtls version 3.1.0 from github will be compiled and installed.
Signed-off-by: Juergen Repp <juergen.repp@sit.fraunhofer.de>
=> images: add ubuntu22.04 with mbedtls 3.1.0.

alpine-3.15.docker.m4, fedora-30.docker.m4, fedora-32.arm32v7.docker.m4, fedora-32.docker.m4, fedora-32.ppc64le.docker.m4, fedora-34-libressl.docker.m4, fedora-34.docker.m4, modules/ubuntu_20.04_base_deps.m4, opensuse-leap-15.2.docker.m4, opensuse-leap.docker.m4, ubuntu-18.04.docker.m4, ubuntu-22.04-mbedtls-3.1.docker.m4, ubuntu-22.04.docker.m4
This PR is associated with https://github.com/tpm2-software/tpm2-tss/pull/2479 to introduce a USB TPM (LetsTrust-TPM2Go) TCTI module. This PR alone may not suffice, please advise.
- alpine-3.15
- fedora-32
- opensuse-leap
- ubuntu-18.04
- ubuntu_20.04
- ubuntu-22.04
- ubuntu-22.04-mbedtls-3.1
Signed-off-by: wenxin.leong <wenxin.leong@infineon.com>
=> Add libusb-1.0-0-dev

fedora-32.ppc64le.docker.m4, modules/pip3.m4, ubuntu-20.04.arm32v7.docker.m4
bcrypt needs to be pinned for the following images:
- fedora-32.ppc64le
- ubuntu-20.04.arm32v7
This is due to Rust now being required since 4.0 of bcrypt per the CHANGELOG here:
- https://pypi.org/project/bcrypt/4.0.1/
Thus pin it to the last pre 4.0 release of 3.2.2
Signed-off-by: William Roberts <william.c.roberts@intel.com>
=> modules/pip3: allow pinning of bcrypt version

.github/workflows/main.yml, .github/workflows/publish.yml, alpine-3.15-ossl3.docker.m4
After the installation of ossl3 with apk curl-dev can't be installed via apk.
Thus curl 7.80 has to be compiled.
Signed-off-by: Juergen Repp <juergen.repp@sit.fraunhofer.de>
=> images: add alpine image with openssl3

.github/workflows/main.yml, .github/workflows/publish.yml, fedora-32-ossl3.docker.m4, opensuse-leap-ossl3.docker.m4
The dev package of openssl is removed and openssl3 is compiled and installed.
Because this will only temporary used until ossl3 is available on
distributions this workaround was chosen, because no changes on
the other m4 files were needed.
The imagess ubuntu-20.04, fedora-32, and opensuse-leap were extended.
Signed-off-by: Juergen Repp <juergen.repp@sit.fraunhofer.de>
=> images: add images with openssl3.

alpine-3.15.docker.m4, fedora-32.docker.m4, fedora-32.ppc64le.docker.m4, fedora-34-libressl.docker.m4, fedora-34.docker.m4, modules/ubuntu_20.04_base_deps.m4, opensuse-leap-15.2.docker.m4, opensuse-leap.docker.m4, ubuntu-18.04.docker.m4, ubuntu-22.04-mbedtls-3.1.docker.m4, ubuntu-22.04.docker.m4
This PR is associated with https://github.com/tpm2-software/tpm2-tss/pull/2503 to introduce a USB TPM (FTDI MPSSE USB to SPI bridge) TCTI module.
The TCTI module supports both libftdi-dev (version 0.x) and libftdi1-dev (version 1.x). Depending on the distro, either of these library is installed.
Signed-off-by: wenxin.leong <wenxin.leong@infineon.com>
=> Add libftdi-dev to all images

.github/workflows/main.yml, .github/workflows/manual.yml, .github/workflows/publish.yml
By using the latest release of actions, the following issues can be addressed:
- Fix the warning "Node.js 12 actions are deprecated" which is triggered by actions/checkout@v2, docker/setup-buildx-action@v1, docker/login-action@v1, docker/build-push-action@v2.
- Fix a known stability issue ([#761](https://github.com/docker/build-push-action/issues/761)) that arises when pushing to GHCR. This issue has been resolved in the latest release. Changes have been made to follow the recommended sequence provided at https://github.com/marketplace/actions/build-and-push-docker-images. These changes are:
1. Name: Set up QEMU.
Uses: docker/setup-qemu-action@v2.
2. Name: Set up Docker Buildx.
Uses: docker/setup-buildx-action@v2.
3. Name: Login to Docker Hub.
Uses: docker/login-action@v2.
4. Name: Build …
=> [GitHub Actions] Fix deprecated warnings and failures that may occur when pushing to GHCR.

opensuse-leap.docker.m4
GitHub Actions failed for https://github.com/tpm2-software/tpm2-pkcs11 due to the absence of the ssh-keygen binary.
The ssh-keygen binary is absent from opensuse-leap >= 15.4. In older versions, this binary was indirectly installed through a chain of packages: git -> git-core -> openssh-clients -> openssh-common. However, in later versions, git-core no longer installs openssh-clients. Therefore, we need to install openssh-common manually.
=> Correct a missing dependency in opensuse-leap >= 15.4

.github/workflows/main.yml, .github/workflows/publish.yml, fedora-32.docker.m4, fedora-32.ppc64le.docker.m4, modules/ibmtpm1682.m4, modules/pip3-withoutupgrade.m4, opensuse-leap-15.2.docker.m4, opensuse-leap.docker.m4, ubuntu-24.04.docker.m4
The pip venv setup is skipped and passed by using "--break-system-packages" and setting "ENV PIP_BREAK_SYSTEM_PACKAGES=1"
The pip upgrade is not necessary.
=> ubuntu24.04 initial commit.
